---
abstract: 'A test distribution using similar file names'
author:
  - 'Helmut Wollmersdorfer <helmut.wollmersdorfer@gmx.at>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.035
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jane-Doe
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/wollmers/Jane-Doe/issues
  homepage: https://github.com/wollmers/Jane-Doe
  repository: https://github.com/wollmers/Jane-Doe.git
version: 0.00
x_contributors:
  - 'Helmut Wollmersdorfer <helmut@wollmersdorfer.at>'
